# Generated by Django 6.0.5 on 2026-06-01 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
    ]
